
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 16 18:18:55 UYT 2015
//----------------------------------------------------

package com.language;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 35;
  public static final int DISTINTO = 17;
  public static final int SHIFT_DER = 10;
  public static final int EXPONENTE = 6;
  public static final int RPARENCORCHETE = 34;
  public static final int RESTA = 3;
  public static final int DIVISION_ENTERA = 7;
  public static final int LPAREN = 27;
  public static final int INT = 37;
  public static final int SEPARADOR = 25;
  public static final int BXOR = 14;
  public static final int RPAREN = 28;
  public static final int NOT = 23;
  public static final int AND = 15;
  public static final int IGUAL = 18;
  public static final int OR = 16;
  public static final int COMMA = 32;
  public static final int LPARENCUADRADO = 30;
  public static final int BAND = 12;
  public static final int SUMA = 2;
  public static final int ID = 36;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int COMPLEMENTO = 11;
  public static final int EQUAL = 24;
  public static final int error = 1;
  public static final int MODULO = 8;
  public static final int MENOR = 20;
  public static final int SHIFT_IZQ = 9;
  public static final int MAYOR = 19;
  public static final int BOR = 13;
  public static final int LPARENCORCHETE = 33;
  public static final int RPARENCUADRADO = 31;
  public static final int MAYOR_IGUAL = 22;
  public static final int FLOAT = 38;
  public static final int END = 26;
  public static final int LONG = 41;
  public static final int STRING = 39;
  public static final int MENOR_IGUAL = 21;
  public static final int DIVISION = 4;
  public static final int PRINT = 29;
  public static final int MULTIPLICACION = 5;
}

