
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 17 22:41:43 UYT 2015
//----------------------------------------------------

package com.language;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 36;
  public static final int DISTINTO = 17;
  public static final int SHIFT_DER = 10;
  public static final int EXPONENTE = 6;
  public static final int RPARENCORCHETE = 35;
  public static final int RESTA = 3;
  public static final int DIVISION_ENTERA = 7;
  public static final int LPAREN = 28;
  public static final int INT = 45;
  public static final int SEPARADOR = 25;
  public static final int BXOR = 14;
  public static final int RPAREN = 29;
  public static final int NOT = 23;
  public static final int AND = 15;
  public static final int IGUAL = 18;
  public static final int OR = 16;
  public static final int COMMA = 33;
  public static final int LPARENCUADRADO = 31;
  public static final int BAND = 12;
  public static final int SUMA = 2;
  public static final int IF = 39;
  public static final int ID = 44;
  public static final int ENDWHILE = 38;
  public static final int DOT = 26;
  public static final int BOOLEAN = 48;
  public static final int EOF = 0;
  public static final int COMPLEMENTO = 11;
  public static final int EQUAL = 24;
  public static final int error = 1;
  public static final int MODULO = 8;
  public static final int MENOR = 20;
  public static final int FDEF = 42;
  public static final int SHIFT_IZQ = 9;
  public static final int MAYOR = 19;
  public static final int FRETURN = 43;
  public static final int ENDIF = 41;
  public static final int ELSE = 40;
  public static final int BOR = 13;
  public static final int LPARENCORCHETE = 34;
  public static final int WHILE = 37;
  public static final int RPARENCUADRADO = 32;
  public static final int MAYOR_IGUAL = 22;
  public static final int FLOAT = 46;
  public static final int END = 27;
  public static final int LONG = 49;
  public static final int STRING = 47;
  public static final int MENOR_IGUAL = 21;
  public static final int DIVISION = 4;
  public static final int PRINT = 30;
  public static final int MULTIPLICACION = 5;
}

