
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 04 22:02:14 UYT 2015
//----------------------------------------------------

package com.language;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DECIMAL = 13;
  public static final int INTEGRAL = 12;
  public static final int EQUAL = 6;
  public static final int STRING = 14;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int SEPARADOR = 7;
  public static final int ID = 11;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int TIMES = 4;
  public static final int LPAREN = 9;
  public static final int END = 8;
}

